---
language: ruby
os:
  - osx

before_install:
  - brew update
  - brew install ansible

install:
  # Check ansible version
  - ansible --version

script:
  - cd tests && ansible-playbook -i inventory test.yml --syntax-check
  - cd tests && ansible-playbook -i inventory test.yml

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
